-- CreateEnum
CREATE TYPE "PluginScope" AS ENUM ('WORKSPACE', 'PLATFORM');

-- Prisma also wanted `ALTER COLUMN "searchVector" DROP DEFAULT` on Comment and
-- Issue here. Both columns are generated by Postgres itself, Prisma's diff
-- engine does not understand that, and Postgres rejects the statement. Removed
-- as in the migration before this one; it has nothing to do with the plugin
-- columns below. Both new columns have a default, so rows that already exist
-- (workspace plugins, as before) need no backfill.

-- AlterTable
ALTER TABLE "Plugin" ADD COLUMN     "config" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "scope" "PluginScope" NOT NULL DEFAULT 'WORKSPACE';
