{{- if and .Values.postgresql.enabled (not .Values.externalDatabase.existingSecretUrlKey) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "barynt.fullname" . }}-postgres
  labels:
    {{- include "barynt.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    {{- include "barynt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
