-- Prisma also wanted `ALTER COLUMN "searchVector" DROP DEFAULT` on Comment and
-- Issue here. Both columns are generated by Postgres itself, Prisma's diff
-- engine does not understand that, and Postgres rejects the statement. Removed
-- as in the earlier plugin migrations; it has nothing to do with the table below.

-- CreateTable
CREATE TABLE "PluginStore" (
    "id" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "official" BOOLEAN NOT NULL DEFAULT false,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PluginStore_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PluginStore_key_key" ON "PluginStore"("key");
