-- CreateEnum
CREATE TYPE "PluginSource" AS ENUM ('STORE', 'UPLOAD', 'DIRECTORY');

-- CreateEnum
CREATE TYPE "PluginStatus" AS ENUM ('ENABLED', 'DISABLED');

-- Prisma also wanted `ALTER COLUMN "searchVector" DROP DEFAULT` on Comment and
-- Issue here. Both columns are generated by Postgres itself, Prisma's diff
-- engine does not understand that, and Postgres rejects the statement. Removed
-- as in 20260916172104_add_issue_due_date_and_estimates; it has nothing to do
-- with the plugin tables below.

-- CreateTable
CREATE TABLE "Plugin" (
    "id" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "status" "PluginStatus" NOT NULL DEFAULT 'ENABLED',
    "source" "PluginSource" NOT NULL,
    "origin" TEXT,
    "integrity" TEXT NOT NULL,
    "installedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Plugin_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PluginWorkspace" (
    "pluginId" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "config" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PluginWorkspace_pkey" PRIMARY KEY ("pluginId","workspaceId")
);

-- CreateIndex
CREATE INDEX "PluginWorkspace_workspaceId_idx" ON "PluginWorkspace"("workspaceId");

-- AddForeignKey
ALTER TABLE "PluginWorkspace" ADD CONSTRAINT "PluginWorkspace_pluginId_fkey" FOREIGN KEY ("pluginId") REFERENCES "Plugin"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PluginWorkspace" ADD CONSTRAINT "PluginWorkspace_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
