/**
 * Builds `lib/icons/bundle.generated.ts`: the icons the app actually uses,
 * cut out of the `@iconify-json/*` sets, so `<Icon icon="lucide:…" />`
 * renders from the app's own bundle instead of fetching from
 * api.iconify.design at runtime (see BARY-45).
 *
 *   bun run icons:build     regenerate after adding or removing an icon
 *   bun run icons:check     fail if the generated file is out of date
 *
 * An icon counts as used when its `prefix:name` shows up as a string
 * literal in app/, components/, features/ or lib/ — whatever prefix has a
 * `@iconify-json/<prefix>` devDependency installed. Names assembled at
 * runtime can't be seen here; they still work, just via the API fallback.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const SOURCE_DIRS = ["app", "components", "features", "lib"];
const OUTPUT = join(ROOT, "lib/icons/bundle.generated.ts");
const LITERAL = /["'`]([a-z0-9-]+):([a-z0-9-]+)["'`]/g;

interface IconEntry {
  body: string;
  width?: number;
  height?: number;
}
interface AliasEntry {
  parent: string;
  [key: string]: unknown;
}
interface IconSet {
  prefix: string;
  width?: number;
  height?: number;
  icons: Record<string, IconEntry>;
  aliases?: Record<string, AliasEntry>;
}

/** Prefixes with an installed `@iconify-json/<prefix>` set. */
export function installedPrefixes(): string[] {
  const dir = join(ROOT, "node_modules/@iconify-json");
  return existsSync(dir) ? readdirSync(dir).sort() : [];
}

function* sourceFiles(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "generated" || entry.name.endsWith(".generated.ts")) {
      continue;
    }
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* sourceFiles(path);
    else if (/\.(ts|tsx)$/.test(entry.name)) yield path;
  }
}

/** `prefix → sorted names` for every icon literal found in the source. */
export function collectIconNames(): Map<string, string[]> {
  const prefixes = new Set(installedPrefixes());
  const found = new Map<string, Set<string>>();
  for (const sourceDir of SOURCE_DIRS) {
    for (const file of sourceFiles(join(ROOT, sourceDir))) {
      for (const [, prefix, name] of readFileSync(file, "utf8").matchAll(
        LITERAL,
      )) {
        if (!prefixes.has(prefix)) continue;
        if (!found.has(prefix)) found.set(prefix, new Set());
        found.get(prefix)?.add(name);
      }
    }
  }
  return new Map(
    [...found]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([p, n]) => [p, [...n].sort()]),
  );
}

/** The subset of one icon set: the wanted icons plus what aliases point at. */
function subset(prefix: string, names: string[]) {
  const set: IconSet = JSON.parse(
    readFileSync(
      join(ROOT, `node_modules/@iconify-json/${prefix}/icons.json`),
      "utf8",
    ),
  );
  const icons: Record<string, IconEntry> = {};
  const aliases: Record<string, AliasEntry> = {};
  const missing: string[] = [];

  const take = (name: string): boolean => {
    if (set.icons[name]) {
      icons[name] = set.icons[name];
      return true;
    }
    const alias = set.aliases?.[name];
    if (alias) {
      aliases[name] = alias;
      return take(alias.parent);
    }
    return false;
  };
  for (const name of names) if (!take(name)) missing.push(`${prefix}:${name}`);

  const result: Record<string, unknown> = { prefix };
  if (set.width) result.width = set.width;
  if (set.height) result.height = set.height;
  result.icons = icons;
  if (Object.keys(aliases).length > 0) result.aliases = aliases;
  return { collection: result, missing };
}

export function renderBundle(): { source: string; missing: string[] } {
  const collections: Record<string, unknown>[] = [];
  const missing: string[] = [];
  for (const [prefix, names] of collectIconNames()) {
    const { collection, missing: gone } = subset(prefix, names);
    collections.push(collection);
    missing.push(...gone);
  }
  const source = `// Generated by scripts/build-icons.ts — do not edit.
// Regenerate with \`bun run icons:build\` after adding or removing an icon.
import type { IconifyJSON } from "@iconify/react";

export const ICON_COLLECTIONS: IconifyJSON[] = ${JSON.stringify(collections, null, 2)};
`;
  return { source, missing };
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const { source, missing } = renderBundle();
  if (missing.length > 0) {
    console.error(`Icons not found in their set:\n  ${missing.join("\n  ")}`);
    process.exit(1);
  }
  if (check) {
    const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8") : "";
    if (current !== source) {
      console.error(
        "lib/icons/bundle.generated.ts is out of date — run `bun run icons:build`.",
      );
      process.exit(1);
    }
    console.log("Icon bundle is up to date.");
  } else {
    writeFileSync(OUTPUT, source);
    console.log(`Wrote ${OUTPUT}`);
  }
}
